<?php

use Illuminate\Database\Seeder;

class GoatsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('goats')->insert(array(

			// Goal - 1
            array(
				'type' => 'G',
				'parent_id' => null,
				'description' => 'Transform Communities',
                'complete' => false,
				'priority' => 0,
                'goal_type' => 'B',
				'due_date' => null ,
				'budget' => 0,
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
				'bid' => 1,
                'department_id' => null,
                'success_measure' => null
            ),

			// Goal - 2
            array(
				'type' => 'G',
				'parent_id' => null,
				'description' => 'Evolve our digital environment',
                'complete' => false,
				'priority' => 0,
                'goal_type' => 'B',
				'due_date' => null ,
				'budget' => 0,
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
				'bid' => 1,
                'department_id' => null,
                'success_measure' => null
            ),

			// Goal - 3
            array(
				'type' => 'G',
				'parent_id' => null,
				'description' => 'Act as a catalyst for learning, discovery and creating',
                'complete' => false,
				'priority' => 0,
                'goal_type' => 'B',
				'due_date' => null ,
				'budget' => 0,
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
				'bid' => 1,
                'department_id' => null,
                'success_measure' => null
            ),

			// Goal - 4
            array(
				'type' => 'G',
				'parent_id' => null,
				'description' => 'Transition the way we do business',
				'priority' => 0,
                'complete' => false,
                'goal_type' => 'B',
				'due_date' => null ,
				'budget' => 0,
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
				'bid' => 1,
                'department_id' => null,
                'success_measure' => null
            ),

			// Objective - 5
            array(
				'type' => 'O',
				'parent_id' => 1,
    			'description' => 'We identify and meet community needs',
                'complete' => false,
    			'priority' => 1,
                'goal_type' => 'B',
				'due_date' => Carbon\Carbon::createFromDate(2016, 1, 1),
				'budget' => 0,
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
				'bid' => 1,
                'department_id' => null,
                'success_measure' => null
			),

            // Action - 6
            array('type' => 'A',
                'parent_id' => 5,
                'description' => 'Review public computing needs and develop strategies to meet those needs',
                'priority' => 3,
                'complete' => true,
                'goal_type' => 'B',
                'due_date' => Carbon\Carbon::createFromDate(2017, 3, 1),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 1,
                'success_measure' => 'Achieve an 90% satisfaction rating; Increase computer usage by 20%'
            ),

			// Task - 7
            array('type' => 'T',
				'parent_id' => 6,
    			'description' => 'Implement approved recommendations from the 2015 Public Computing Report',
    			'priority' => 2,
                'complete' => true,
                'goal_type' => 'B',
				'due_date' => Carbon\Carbon::createFromDate(2017, 3, 1),
				'budget' => 0,
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
				'bid' => 1,
                'department_id' => 2,
                'success_measure' => null),

			// Task - 8
            array('type' => 'T',
				'parent_id' => 6,
    			'description' => 'Hire more people to help upgrade LibOnline to the latest version (4.9)',
                'complete' => true,
    			'priority' => 3,
                'goal_type' => 'B',
				'due_date' => Carbon\Carbon::createFromDate(2017, 6, 12),
				'budget' => 0,
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
				'bid' => 1,
                'department_id' => 3,
                'success_measure' => null),

			// Task - 9
            array('type' => 'T',
				'parent_id' => 6,
                'complete' => false,
    			'description' => 'Pay wireless bill',
    			'priority' => 1,
                'goal_type' => 'B',
				'due_date' => Carbon\Carbon::createFromDate(2016, 5, 3),
				'budget' => 0,
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
				'bid' => 1,
                'department_id' => 4,
                'success_measure' => null),

			// Objective - 10
            array('type' => 'O',
				'parent_id' => 1,
                'description' => 'We reduce barriers to accessing library services',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'B',
				'due_date' => Carbon\Carbon::createFromDate(2016, 7, 4),
				'budget' => 10000,
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
				'bid' => 1,
                'department_id' => null,
                'success_measure' => null),

			// Action - 11
            array('type' => 'A',
				'parent_id' => 10,
                'description' => 'Establish a fine-free day to take place every second year',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'B',
				'due_date' => Carbon\Carbon::createFromDate(2016, 5, 2),
				'budget' => 0,
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
				'bid' => 1,
                'department_id' => 5,
                'success_measure' => null),

			// Task - 12
            array('type' => 'T',
				'parent_id' => 11,
                'description' => 'Provide planning assistance to the Customer Payments team to implement the necessary changes to support a fine-free day',
                'priority' => 1,
                'complete' => false,
                'goal_type' => 'B',
				'due_date' => Carbon\Carbon::createFromDate(2016, 7, 6),
				'budget' => 0,
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
				'bid' => 1,
                'department_id' => 1,
                'success_measure' => null),

			// Action - 13
            array('type' => 'A',
				'parent_id' => 10,
                'description' => 'Extend literacy van services to underserved communities in Edmonton and surrounding areas',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'B',
				'due_date' => Carbon\Carbon::createFromDate(2017, 6, 1),
				'budget' => 0,
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
				'bid' => 1,
                'department_id' => 2,
                'success_measure' => 'Increased use and knowledge of EPL services in underserved communities'),

			// Task - 14
            array('type' => 'T',
				'parent_id' => 13,
                'description' => 'Aid in the selection, purchase, and configuration of equipment for the fourth literacy van',
                'priority' => 1,
                'complete' => false,
                'goal_type' => 'B',
				'due_date' => Carbon\Carbon::createFromDate(2015, 7, 6),
				'budget' => 0,
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
				'bid' => 1,
                'department_id' => 3,
                'success_measure' => 'Equipment purchased, configured, and deployed'),

			// Objective - 15
            array('type' => 'O',
				'parent_id' => 2,
                'description' => 'The ease of use and integration of content is praised by customers',
                'priority' => 3,
                'complete' => true,
                'goal_type' => 'B',
				'due_date' => Carbon\Carbon::createFromDate(2017, 6, 7),
				'budget' => 0,
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
				'bid' => 1,
                'department_id' => null,
                'success_measure' => null),

			// Action - 16
			array('type' => 'A',
				'parent_id' => 15,
				'description' => 'Implement a single point of discovery for EPL content',
				'priority' => 2,
                'complete' => true,
                'goal_type' => 'B',
				'due_date' => Carbon\Carbon::createFromDate(2018, 8, 7),
				'budget' => 0,
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
				'bid' => 1,
                'department_id' => 5,
                'success_measure' => 'Achieve an 90% satisfaction rating with services and content'),

            // Task - 17
            array('type' => 'T',
                'parent_id' => 16,
                'description' => 'Liaise with Sirsi Dynix to support CMA\'s Single Sign On (SSO) project',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'B',
                'due_date' => Carbon\Carbon::createFromDate(2018, 8, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 2,
                'success_measure' => 'SSO is implemented'),

            // IT Goal - 18
            array('type' => 'G',
                'parent_id' => null,
                'description' => 'IT Services Goals',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'D',
                'due_date' => Carbon\Carbon::createFromDate(2018, 8, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 2,
                'success_measure' => null),

            // IT Goal - 19
            array('type' => 'O',
                'parent_id' => 18,
                'description' => 'Test Windows 10 in EPL\'s environment and develop a deployment plan ',
                'priority' => 1,
                'complete' => false,
                'goal_type' => 'D',
                'due_date' => Carbon\Carbon::createFromDate(2018, 8, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 2,
                'success_measure' => null),
            
            // IT Goal - 20
            array('type' => 'O',
                'parent_id' => 19,
                'description' => 'Mobile Device Management (MDM) documentation and roll out',
                'priority' => 2,
                'complete' => true,
                'goal_type' => 'D',
                'due_date' => Carbon\Carbon::createFromDate(2018, 8, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 2,
                'success_measure' => null),

            // Events Team Goals - 21
            array('type' => 'G',
                'parent_id' => null,
                'description' => 'Events Team Goals',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'D',
                'due_date' => Carbon\Carbon::createFromDate(2018, 8, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 1,
                'success_measure' => null),

            // Human Resources Goals - 22
            array('type' => 'G',
                'parent_id' => null,
                'description' => 'Human Resources Goals',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'D',
                'due_date' => Carbon\Carbon::createFromDate(2018, 8, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 3,
                'success_measure' => null),

            // Financial Services Goals - 23
            array('type' => 'G',
                'parent_id' => null,
                'description' => 'Financial Services Goals Goals',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'D',
                'due_date' => Carbon\Carbon::createFromDate(2018, 8, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 4,
                'success_measure' => null),

            // Marketing Goals - 24
            array('type' => 'G',
                'parent_id' => null,
                'description' => 'Marketing Goals',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'D',
                'due_date' => Carbon\Carbon::createFromDate(2018, 8, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 5,
                'success_measure' => null),

            // Fund Development Goals - 25
            array('type' => 'G',
                'parent_id' => null,
                'description' => 'Fund Development Goals',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'D',
                'due_date' => Carbon\Carbon::createFromDate(2018, 8, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 6,
                'success_measure' => null),

            // Collection Management and Access Goals - 26
            array('type' => 'G',
                'parent_id' => null,
                'description' => 'Collection Management and Access Goals',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'D',
                'due_date' => Carbon\Carbon::createFromDate(2018, 8, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 7,
                'success_measure' => null),

            // School Aged Services (SAS) Team Goals - 27
            array('type' => 'G',
                'parent_id' => null,
                'description' => 'School Aged Services (SAS) Team Goals',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'D',
                'due_date' => Carbon\Carbon::createFromDate(2018, 8, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 8,
                'success_measure' => null),

            // Community-Led Team Goals - 28
            array('type' => 'G',
                'parent_id' => null,
                'description' => 'Community-Led Team Goals',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'D',
                'due_date' => Carbon\Carbon::createFromDate(2018, 8, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 9,
                'success_measure' => null),

            // Foundational Programming Team Goals - 29
            array('type' => 'G',
                'parent_id' => null,
                'description' => 'Foundational Programming Team Goals',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'D',
                'due_date' => Carbon\Carbon::createFromDate(2018, 8, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 10,
                'success_measure' => null),

            // Membership Services Team Goals - 30
            array('type' => 'G',
                'parent_id' => null,
                'description' => 'Membership Services Team Goals',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'D',
                'due_date' => Carbon\Carbon::createFromDate(2018, 8, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 11,
                'success_measure' => null),

            // Discovery Team Goals - 31
            array('type' => 'G',
                'parent_id' => null,
                'description' => 'Discovery Team Goals',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'D',
                'due_date' => Carbon\Carbon::createFromDate(2018, 8, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 12,
                'success_measure' => null),

            // Objective - 32
            array('type' => 'O',
                'parent_id' => 3,
                'description' => 'act as a catalyst for learning, discovering and creating',
                'priority' => 2,
                'complete' => true,
                'goal_type' => 'B',
                'due_date' => Carbon\Carbon::createFromDate(2017, 2, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 2,
                'success_measure' => null),

            // Action - 33
            array('type' => 'A',
                'parent_id' => 32,
                'description' => 'Develop an Open Data policy that includes how we will use and share our own data; participate in Edmonton\'s Open Data community and support data literacy initiatives.',
                'priority' => 2,
                'complete' => true,
                'goal_type' => 'B',
                'due_date' => Carbon\Carbon::createFromDate(2017, 2, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 2,
                'success_measure' => null),

            // Task - 34
            array('type' => 'T',
                'parent_id' => 33,
                'description' => 'Release more EPL open data to City of Edmonton open data portal.',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'B',
                'due_date' => Carbon\Carbon::createFromDate(2017, 1, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 2,
                'success_measure' => null),

            // Objective - 35
            array('type' => 'O',
                'parent_id' => 3,
                'description' => 'EPL is a staff of learners confident in their abilities to assist customers',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'B',
                'due_date' => Carbon\Carbon::createFromDate(2017, 1, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 2,
                'success_measure' => null),

            // Action - 36
            array('type' => 'A',
                'parent_id' => 35,
                'description' => 'Review technology needs to provide services and implement strategies to meet them',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'B',
                'due_date' => Carbon\Carbon::createFromDate(2017, 1, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 2,
                'success_measure' => null),

            // Task - 37
            array('type' => 'T',
                'parent_id' => 36,
                'description' => 'Support the ILS team\'s implementation of Mobile Circ',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'B',
                'due_date' => Carbon\Carbon::createFromDate(2017, 1, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 2,
                'success_measure' => null),

            // Task - 38
            array('type' => 'T',
                'parent_id' => 36,
                'description' => 'Purchase new iPad kits for each branch currently without one per budget request',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'B',
                'due_date' => Carbon\Carbon::createFromDate(2017, 1, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 2,
                'success_measure' => null),

            // Task - 39
            array('type' => 'T',
                'parent_id' => 36,
                'description' => 'Purchase laptop kits for each branch currently without one per budget request',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'B',
                'due_date' => Carbon\Carbon::createFromDate(2017, 1, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 2,
                'success_measure' => null),

            // Task - 40
            array('type' => 'T',
                'parent_id' => 36,
                'description' => 'In collaboration with DLI, select equipment to replace aging Makerspace equipment',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'B',
                'due_date' => Carbon\Carbon::createFromDate(2017, 1, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 2,
                'success_measure' => null),

            // Task - 41
            array('type' => 'T',
                'parent_id' => 36,
                'description' => 'Implement a regular "What\'s up with that?" style blog post by IT to enhance staff understanding of technology',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'B',
                'due_date' => Carbon\Carbon::createFromDate(2017, 1, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 2,
                'success_measure' => null),

            // Task - 42
            array('type' => 'T',
                'parent_id' => 36,
                'description' => 'Stabilize and standardize the display board environment',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'B',
                'due_date' => Carbon\Carbon::createFromDate(2017, 1, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 2,
                'success_measure' => null),

            // Objective - 43
            array('type' => 'O',
                'parent_id' => 4,
                'description' => 'We have transformed our approach to service delivery and use of physical spaces',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'B',
                'due_date' => Carbon\Carbon::createFromDate(2017, 1, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 2,
                'success_measure' => null),

            // Action - 44
            array('type' => 'A',
                'parent_id' => 43,
                'description' => 'Complete reviews to ensure ongoing improvement of interlibrary loans, custodial, service point operations, and others. ',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'B',
                'due_date' => Carbon\Carbon::createFromDate(2017, 1, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 2,
                'success_measure' => null),

            // Task - 45
            array('type' => 'T',
                'parent_id' => 44,
                'description' => 'Compare IT\'s current ticketing sytems against demos of inexpensive, focused ticketing systems to determine if a migration can and should occur.',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'B',
                'due_date' => Carbon\Carbon::createFromDate(2017, 1, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 2,
                'success_measure' => null),

            // Task - 46
            array('type' => 'T',
                'parent_id' => 44,
                'description' => 'Conduct a literature review of Help Desk best practices to determine how EPL\'s processes can be improved',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'B',
                'due_date' => Carbon\Carbon::createFromDate(2017, 1, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 2,
                'success_measure' => null),

            // Task - 47
            array('type' => 'T',
                'parent_id' => 44,
                'description' => 'Create an Internal Service Level Agreement document outlining IT\'s processes and commitments to its customers',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'B',
                'due_date' => Carbon\Carbon::createFromDate(2017, 1, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 2,
                'success_measure' => null),

            // Task - 48
            array('type' => 'T',
                'parent_id' => 20,
                'description' => 'Create internal documentation for each profile (i.e. Early literacy and Mini-makerspace) applied to EPL iPads by EPL\'s Mobile Device Management software',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'D',
                'due_date' => Carbon\Carbon::createFromDate(2017, 1, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 2,
                'success_measure' => null),

            // Task - 49
            array('type' => 'T',
                'parent_id' => 20,
                'description' => 'Develop and implement an implementation plan for rolling EPL\'s Mobile Device Management tool out to all pre-existing kit iPads',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'D',
                'due_date' => Carbon\Carbon::createFromDate(2017, 1, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 2,
                'success_measure' => null),

            // Task - 50
            array('type' => 'T',
                'parent_id' => 20,
                'description' => 'Complete a cost/benefit analysis of using EPL\'s MDM to secure manager iPads',
                'priority' => 2,
                'complete' => false,
                'goal_type' => 'D',
                'due_date' => Carbon\Carbon::createFromDate(2017, 1, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 2,
                'success_measure' => null),

            // Task - 51
            array('type' => 'T',
                'parent_id' => 19,
                'description' => 'Develop a test plan to determine if EPL is ready to move to Windows 10',
                'priority' => 1,
                'complete' => false,
                'goal_type' => 'D',
                'due_date' => Carbon\Carbon::createFromDate(2018, 8, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 2,
                'success_measure' => null),

            // Task - 52
            array('type' => 'T',
                'parent_id' => 19,
                'description' => 'Determine the budget implications of upgrading to Windows 10',
                'priority' => 1,
                'complete' => false,
                'goal_type' => 'D',
                'due_date' => Carbon\Carbon::createFromDate(2018, 8, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 2,
                'success_measure' => null),

            // Task - 53
            array('type' => 'T',
                'parent_id' => 19,
                'description' => 'Develop a deployment/upgrade plan to migrate to Windows 10 if appropriate',
                'priority' => 1,
                'complete' => false,
                'goal_type' => 'D',
                'due_date' => Carbon\Carbon::createFromDate(2018, 8, 7),
                'budget' => 0,
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
                'bid' => 1,
                'department_id' => 2,
                'success_measure' => null),
        ));
    }
}
